#!/usr/bin/env php
<?php
ini_set('memory_limit','1024M');
if (!$argv[1] || !is_numeric($argv[1])){
    echo "Usage {$argv[0]} <number>\n";
    exit(1);
}
$n = intval($argv[1]);
$a = range(1,$n+1);
shuffle($a); 
echo join("\n",$a);

?>
