#!/usr/bin/ruby
#
# ruby solution for http://www.coderloop.com/puzzles/answerofeverything
# Francesco Laurita <taganaka@gmail.com>
#

File.open(ARGV[0]).each { | line |

    unless line.to_i == 42
        puts line
    else
        break
    end
}

