#!/usr/bin/php
<?php
/**
* PHP solution for http://www.coderloop.com/puzzles/answerofeverything
* Francesco Laurita <taganaka@gmail.com>
*
**/
$fp = fopen($argv[1],"r");

if ($fp === FALSE){
    echo "Unable to open file\n";
    exit(1);
}

$d = 0;
while (fscanf($fp,"%d",$d) != NULL && $d != 42){
    echo "$d\n";
}
fclose($fp);
?>
